package com.example.saferzapp01.States

data class SignupState(
    val activeScreen:Boolean=true,
    val email:String="",
    val errorEmail:String="",
    val isErrorEmail:Boolean=false,
    val userName:String="",
    val errorUserName:String="",
    val isErrorUserName:Boolean=false,
    val fullName:String="",
    val errorFullName:String="",
    val isErrorFullName:Boolean=false,
    val datePickerDialog:Boolean=false,
    val dob:String="",
    val errorDob:String="format: yyyy/mmm/dd",
    val isErrorDate:Boolean=false,
    val religion:String="",
    val errorReligion:String="",
    val isErrorReligion:Boolean=false,
    val gender:String="",
    val errorGender:String="",
    val isErrorGender:Boolean=false,
    val password:String="",
    val errorPassword:String="",
    val isErrorPassword:Boolean=false,
    val passwordHidden:Boolean=true,
    val confirmPassword:String="",
    val errorConfirmPassword:String="",
    val isErrorConfirmPassword:Boolean=false,
    val confirmPasswordHidden:Boolean=true,
    val signup:Boolean=false
)
